name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: run Lighthouse CI
        run: |
          ./node_modules/.bin/lhci autorun --config=./lighthouserc-ci.js
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
